#! /bin/sh

# startup
sxhkd &
redshift -l 51:-114 &
compton -f -C -D 5 --backend glx -b
feh --bg-fill --randomize ~/pictures/wallpapers/
wmname LG3D

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width        1
bspc config window_gap          5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc rule -a Pavucontrol state=floating
bspc rule -a Wicd-client.py state=floating
bspc rule -a Transmission-gtk state=floating
